runtime: nodejs10
service: calculator
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  max_instances: 1
